import './globals.css'
import type { Metadata } from 'next'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import './components/navigation'
import { Navigation } from './components/navigation'
import { UIProvider } from './context/UIContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <Head>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css"
          rel="stylesheet"
        />
        <script
          src="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js"
          async
        ></script>
      </Head> */}
      <body className={inter.className}>
      <UIProvider>
        <header className='bg-black text-white p-4 text-center'>
          {/* <p>Hello World</p> */}
          <Navigation/>
        </header>
        {children}
        </UIProvider>
      </body>
    </html>
  )
}
